baseURL = "https://emilyhill94.github.io/"
languageCode = "en-uk"
title = "Digital Land"
theme = "govuk"
googleAnalytics = "UA-127566551-1"

staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
  global_header_text = "GOV.UK"
  servicename = "Digital Land"
  users = ["Data Maintainer", "Data Modeller", "Policy Maker", "PropTech"]

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "Portfolio"
  url = "/portfolio"
  currentpage = true

  [[params.propositionlinks]]
  name = "Projects"
  url = "/project/"

  [[params.propositionlinks]]
  name = "Prototypes"
  url = "/prototype/"

  [[params.propositionlinks]]
  name = "Glossary"
  url = "/glossary/"

  [[params.propositionlinks]]
  name = "Users"
  url = "/users/"

  [[params.propositionlinks]]
  name = "Events"
  url = "/event/"

  [[params.propositionlinks]]
  name = "Blog posts"
  url = "/blog-post/"

  [[params.footer_meta_links]]
  name = "Cookies"
  url = "/cookies"


[taxonomies]
  tag = "tags"
  pattern = "patterns"
